language: node_js

branches:
  only: master

notifications:
  email: false

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      addons:
        chrome: stable
      before_script:
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - sleep 3
    - os: osx
      osx_image: xcode8.3
